### PR TITLE
Update and rename README.md to sabiork.md

### PR DESCRIPTION
**Pull request by wittigue**

### CODE REVIEW

**Comment by fbergmann** [comment]
@wittigue if i were to merge it the link from the main page will be broken. I'd suggest to leave the readme.md file present, maybe in addition if you have multiple courses. Alternatively the other files pointing to `workshop_2024/hits` need to be changed as well. 

If you still want me to merge it though i will go ahead.

**Comment by wittigue** [comment]
I'm just preparing another file for the SEEK course. That's why I thought to have sabiork.md + seek.md files.
So should we have three files including readme.md or for example readme.md + seek.md?

**Comment by fbergmann** [comment]
This line needs to be updated, probably in any case: 
<https://github.com/copasi/denbi-modsim.github.io/blob/b96965c3c82b094b8f01bab915bf0177d89ea621/index.html#L321>

and the other mentioning is here: 
https://github.com/copasi/denbi-modsim.github.io/blame/b96965c3c82b094b8f01bab915bf0177d89ea621/workshop_2024/README.md#L6

However you want to change that is fine.

**Comment by wittigue** [comment]
OK, I would also change it for the overview pages above. Since there are two different days we would also announce it as two different courses. So people could just join one of these.
And it should be also listed separately for registration if possible.

**Comment by fbergmann** [comment]
I really think everyone should do their own registration. Otherwise the individual registration forms will be too messy.

**Pull request closed without merging**
